language: node_js
node_js: node
# so that chrome works
# see https://github.com/video-dev/hls.js/pull/1710#discussion_r187754754
sudo: required
# don't connect to sauce labs unless running functional tests
# before_install: if [ "${TRAVIS_MODE}" != "funcTests" ]; then unset SAUCE_USERNAME && unset SAUCE_ACCESS_KEY; fi
script: ./scripts/travis.sh
after_script: if [ "${TRAVIS_MODE}" = "funcTests" ]; then echo -n "travis_fold:start:sauce_logs\nSauce connect log:\n" && cat /home/travis/sauce-connect.log && echo -n "\ntravis_fold:end:sauce_logs\n"; fi
env:
  global:
    - SAUCE_USERNAME=mangui
stages:
    # TODO move to after unit tests
  - release
    # TODO move to after unit tests
  - releaseCanary
  - buildAndTest
  - testFuncRequired
  - testFuncOptional
jobs:
  # stage: optional is allowed to be failure
  fast_finish: true
  allow_failures:
    - stage: optional
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: release
      if: tag IS present
      env: TRAVIS_MODE=release
      deploy:
        provider: releases
        api-key:
          secure: "UrDfvgVXoHiAIbV+tjSCx+qfSVNVD9jonC+5fT0sAiYBkK1zogAJAwD2CSW+btX5lpbgcjit0qj6Ts/fE6Nayr/XZ0HRjlajQVu28XcwP0nkzjuPhoakgPioNCG8y9KvMs9ATNz8uKVS9X0kAMAzxkn569VhV3mGM2Rq880eyr3lxspCG8KIoPv8z5k6dgpi9fnLtO6Ic/iQjBtfg3ywYz71LEzLIMqBvuW6r/kiqFq6DJxFnbRqiyP3p7XUrkALTyXFz5OGde+mQcMwsullGRs+Q8ubmd8Y1A7mplIEO0iRA7jm/Mz3W2Xo/NpLznrqRQDUb6N1NU6TTVJRVceXS66LGPUbBjDh5nunYv2YHXsUR0LUeUKZWmcMwa74dTlKgT2p/t6HaT+VejvvDLQaIxwzccIm8uMUZsMEq9qn4qE0a08H2VAiacHoEgWCjxEfo0v0bNIMr3+OK0EfZecDh6538zEGQ2CmP7JyJw+O82mpbZq5a1j4svYpRMTEKc8gZ+Fp0h2bUH+p95XmQZTmr/utP1fxJkuiZOG70ZgGG1vPsAPgyi3lRbsFQG7rPX08AfMplsg013PKfP+R/5pucoatGHYpgBEsrtl8SC5hyx33soCBIZtnKrWQ4Ct60gRM8ivWfGoMUXMhK1r6KQP/zts2LvDRheECyOV6JBpG6+w="
        file_glob: true
        file: dist/*
        draft: true
        skip_cleanup: true
        on:
          tags: true
    # publish canary package if on master
    - stage: releaseCanary
      if: branch = master AND type != pull_request
      env: TRAVIS_MODE=releaseCanary
    # Required tests
    - stage: buildAndTest
      env:   TRAVIS_MODE=build
    - stage: buildAndTest
      env:   TRAVIS_MODE=unitTests
    - stage: testFuncRequired
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="Windows 10"
    # Optional Func tests
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=firefox             OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="Windows 7"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=firefox             OS="Windows 7"
    # - stage: optional
    #  env:   TRAVIS_MODE=funcTests UA=MicrosoftEdge       OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 8.1"  UA_VERSION="11.0"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA="internet explorer" OS="Windows 10"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=chrome              OS="OS X 10.11"
    # - stage: testFuncOptional
    #  env:   TRAVIS_MODE=funcTests UA=firefox     OS="OS X 10.11"
    - stage: testFuncOptional
      env:   TRAVIS_MODE=funcTests UA=safari              OS="OS X 10.11" UA_VERSION="9.0"
addons:
  sauce_connect: true
  jwt:
    secure: TxJT041jqRf4raCwtNJRb0rz2gGvEaADZjWO41UQND2+YIZ//S9qB2C4YyrL1BBsn8/ebdHr0cd18PwCzoBSEmoCdoAWXmqBaaLvM1DOeQkKJbU3+pFmWtv1qGqRXJLEAysNvzhG0sLdvBc0M7a/CWxqRfx1O3lGhLnTlAW33LlQndjJ8vh3SGQm8HxFR1503ujPd7V1jGwduVwaQp4zbAKTnQ4MLugmJf6UKiTc+YILMrVWOwipOIyYHh2GqbChd/v1PXff26XCNJXcaRZKJ8JosWyBpq5t4zlPO0qDfHpqbEuYK44xm4vzbZS94P/KF8BYzdtxQYLrxoS1UlnUYU7RmzqgL3y3AM7nzX/cXvJcoNXfUK2BpsB754XNyQfRmXOdRiHoC8+wwPqGkH/KCrmS4UIOqv4THfmDbrtewfcDTgKOzHxGcT1IsUq9BTxMNtxSwpHTHUXTXrzpS/UBDvrlc+9qPTqf+e6QL1aG+JT5sOg5REm2hMy0j18/Kr+HLXkehxEgJ6JrybyHUkkJrfcuWgVDu7Lv3cxlrtSMXi7TIwSB75NMoM8AE71GEVjXwpOw/0giwnmGsJNNi01ztod0UFe2V2rS+yPI1WNZIJ7Fw66U0oOKJ1rb4Iksl86n5Y2snHsxK8q5jhKaAaiWgGK5kVTAgF89t/GXYyNH6cI=
